/**
 * Creatable instance classes and services available in OVERDARE Studio.
 *
 * Source of truth: the `--#METADATA#` header of
 *   ~/.overdare/updates/runtime/assets/lua/overdare-types.d.lua
 * (auto-generated by OVERDARE; mirrors the Roblox API surface).
 *
 * Used for `instance.upsert` validation and to give the model an accurate
 * list of what it can create.
 */

export const CREATABLE_INSTANCES = [
  "ActionRunner", "ActionSequence", "ActionSequenceService", "AngularVelocity",
  "Animation", "AnimationTrack", "Animator", "Atmosphere", "Attachment",
  "Backpack", "BackpackItem", "BasePart", "BaseScript", "Beam", "BillboardGui",
  "BindableEvent", "Bone", "BoolValue", "Camera", "CharacterMesh",
  "CollectionService", "Constraint", "ContextActionService", "CoreGui",
  "DataModel", "DataStore", "DataStoreGetOptions", "DataStoreIncrementOptions",
  "DataStoreInfo", "DataStoreKeyInfo", "DataStoreKeyPages",
  "DataStoreListingPages", "DataStoreService", "DataStoreSetOptions", "Fill",
  "Folder", "FormFactorPart", "Frame", "GenericSettings", "GlobalDataStore",
  "GuiBase2d", "GuiButton", "GuiObject", "HttpService", "Humanoid",
  "HumanoidDescription", "ImageButton", "ImageLabel", "InputObject", "Instance",
  "IntValue", "LayerCollector", "Light", "Lighting", "LinearVelocity",
  "LocalScript", "LocalizationService", "LuaSourceContainer",
  "MarketplaceService", "MaterialService", "MaterialVariant", "MeshPart",
  "Model", "ModuleScript", "Mouse", "NumberValue", "OrderedDataStore",
  "Outline", "OverlayBase", "PVInstance", "Pages", "Part", "ParticleEmitter",
  "PhysicsService", "Player", "PlayerGui", "PlayerScripts", "Players",
  "PointLight", "ProximityPrompt", "ProximityPromptService", "RemoteEvent",
  "ReplicatedStorage", "RunService", "ScreenGui", "Script", "ScrollingFrame",
  "ServerScriptService", "ServerStorage", "ServiceProvider", "SimulationBall",
  "Skeleton", "Sound", "SoundGroup", "SoundService", "SpawnLocation",
  "SpotLight", "StarterCharacterScripts", "StarterGui", "StarterPack",
  "StarterPlayer", "StarterPlayerScripts", "StringValue", "SurfaceGui",
  "SurfaceGuiBase", "Team", "Teams", "TeleportAsyncResult", "TeleportOptions",
  "TeleportService", "TextButton", "TextLabel", "Tool", "Trail", "Translator",
  "Tween", "TweenBase", "TweenService", "UIAspectRatioConstraint",
  "UIGridLayout", "UIGridStyleLayout", "UIListLayout", "UserGameSettings",
  "UserInputService", "UserSettings", "ValueBase", "VFXPreset", "VectorForce",
  "Workspace", "WorldRankService", "WorldRoot", "WrapLayer", "WrapTarget",
] as const;

export const SERVICES = [
  "ActionSequenceService", "CollectionService", "ContextActionService",
  "DataStoreService", "HttpService", "Lighting", "LocalizationService",
  "MarketplaceService", "MaterialService", "PhysicsService", "Players",
  "ProximityPromptService", "ReplicatedStorage", "RunService",
  "ServerScriptService", "ServerStorage", "SoundService", "TeleportService",
  "TweenService", "UserInputService", "Workspace", "WorldRankService",
] as const;

export type CreatableInstance = (typeof CREATABLE_INSTANCES)[number];

const creatableSet = new Set<string>(CREATABLE_INSTANCES);
export const isCreatableInstance = (name: string): boolean =>
  creatableSet.has(name);
